version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_LAND_TOKEN_ADDRESS=0x3d550Bef105d71DDeB9184A9b0EB3Dde7567C051
      - NEXT_PUBLIC_LAND_MARKET_ADDRESS=0x19FcA6112B6C4ced0f09Db315F14B8B0ddEE8598
      - NEXT_PUBLIC_LAND_SWAP_ADDRESS=0x7A8aB0187eB080b66919f8166e0e91EB16667557
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-}
      - BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_WALLETCONNECT_METADATA_URL=http://localhost:3000
      - NEXT_PUBLIC_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY:-}
      - APP_MODE=development
      - USE_MOCK_SERVICE=${USE_MOCK_SERVICE:-true}
      - ENABLE_BLOCKCHAIN_LISTENER=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - WHAT3WORDS_API_KEY=${WHAT3WORDS_API_KEY:-}
      - USE_MOCK_SERVICE=${USE_MOCK_SERVICE:-true}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY:-}
      - LAND_TOKEN_ADDRESS=0x3d550Bef105d71DDeB9184A9b0EB3Dde7567C051
      - LAND_MARKET_ADDRESS=0x19FcA6112B6C4ced0f09Db315F14B8B0ddEE8598
      - LAND_SWAP_ADDRESS=0x7A8aB0187eB080b66919f8166e0e91EB16667557
      - BLOCKCHAIN_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY:-}
      - VERIFIER_PRIVATE_KEY=${VERIFIER_PRIVATE_KEY:-}
      - ENABLE_BLOCKCHAIN_LISTENER=true
      - BLOCKCHAIN_WS_URL=wss://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./blockchain/artifacts:/app/blockchain/artifacts
      - /app/node_modules
